export const ActionTypes = {
  SET_MODE: 'SET_MODE',

  ADD_NODE: 'ADD_NODE',
  UPDATE_NODE: 'UPDATE_NODE',
  DELETE_NODE: 'DELETE_NODE',

  ADD_EDGE: 'ADD_EDGE',
  UPDATE_EDGE: 'UPDATE_EDGE',
  DELETE_EDGE: 'DELETE_EDGE',

  REPLACE_NODES: 'REPLACE_NODES',

  SET_SELECTION: 'SET_SELECTION',
  SET_VIEW: 'SET_VIEW',
  SET_INTERACTION: 'SET_INTERACTION',

  SET_UI: 'SET_UI',

  COMMIT_HISTORY: 'COMMIT_HISTORY',
  UNDO: 'UNDO',
  REDO: 'REDO',

  LOAD_PROJECT: 'LOAD_PROJECT',
  RESET: 'RESET',
};
